name: campus_eventos
description: "Cartelera de eventos universitarios: consulta, filtrado por categoria y registro de interes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/

  fonts:
    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZillaSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ZillaSlab-Bold.ttf
          weight: 700
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
